# ------------------------------------------------------------------------------
# Copyright 2021 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

[package]
name = "logger"
version = "0.1.0"
edition = "2021"

[dependencies]
knx_rs = { path = "../knx_rs" }
knxproj = { path = "../knxproj" }
clap = "2.33.3"
log = "0.4.14"
env_logger = "0.9.0"
serial = "0.4.0"