[package]
name = "knx_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
regex = "1.6.0"
syn = {version="1.0.99",features=["full", "fold", "extra-traits"]}
quote = "1.0.21"
proc-macro2 = "1.0.43"